name: notifyme
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^19.3.1
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  http: ^1.4.0
  flutter_app_badge: ^2.0.2
  timezone: ^0.10.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/icon.png


flutter:

  uses-material-design: true

  assets:
    - assets/images/icon.png
    - assets/images/splash_icon.png

  