name: shopping_list
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_analytics: ^12.0.0

  # State Management
  get: ^4.7.2

  # UI
  google_fonts: ^6.3.0
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1

  # Utilities
  uuid: ^4.5.1
  intl: ^0.20.2

  firebase_app_check: ^0.4.0
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2

  # Invite Code
  share_plus: ^7.0.0
  flutter_spinkit: ^5.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/app_icon.png


flutter:
  uses-material-design: true

  assets:
    - assets/images/app_icon.png
